#!/usr/bin/env zsh

# my configs
export DOTFILES=$HOME/dotfiles

# XDG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$XDG_CONFIG_HOME/.local/share
export XDG_CACHE_HOME=$XDG_CONFIG_HOME/.cache

# Term
export TERM=xterm-256color

# Editor
export EDITOR="nvim"
export VISUAL="nvim"

# ZSH
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file
export HISTTIMEFORMAT="[%F %T] "

# FZF stuff
export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git"'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Go stuff
export GOPATH=$HOME/.go
export GOBIN=$GOPATH/bin
export GOTELEMETRYDIR=$XDG_DATA_HOME/go-telemetry
export GOMODCACHE=$GOPATH/pkg/mod
export GOCACHE=$XDG_CACHE_HOME/go-build

# Path
ALLPATHS=(
	"$HOME/.local/bin"
	"/usr/local/go/bin"
	"$HOME/.cargo/bin"
)
printf -v NEWPATHS "%s:" "${ALLPATHS[@]}"
export PATH=${NEWPATHS}${PATH}


